apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: books-ingress
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location /api/books {
        if ($request_method = GET) {
          proxy_pass http://books-get-service:8080;
        }
        if ($request_method = POST) {
          proxy_pass http://books-post-service:8080;
        }
        if ($request_method = PUT) {
          proxy_pass http://books-put-service:8080;
        }
        if ($request_method = DELETE) {
          proxy_pass http://books-delete-service:8080;
        }
      }
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        # Redireccionar la raíz al frontend
        - path: /
          pathType: Prefix
          backend:
            service:
              name: books-frontend-service
              port:
                number: 80

        # Este path activa el bloque del server-snippet
        - path: /api/books
          pathType: Prefix
          backend:
            service:
              name: dummy-service
              port:
                number: 80
