apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-templates
  namespace: default
data:
  main-template: |
    worker_processes {{.WorkerProcesses}};
    events {
      worker_connections {{.MaxWorkerConnections}};
    }
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      sendfile on;
      keepalive_timeout 65;
      include /etc/nginx/conf.d/*.conf;
    }
  ingress-template: |
    {{range $ingress := .Ingresses}}
    {{range $rule := $ingress.Rules}}
    server {
      listen 80;
      server_name {{$rule.Host}};
      {{range $path := $rule.Paths}}
      location {{$path.Path}} {
        {{if eq $path.Path "/api/books"}}
        if ($request_method = GET) {
          proxy_pass http://books-get-service.default.svc.cluster.local:8080;
        }
        if ($request_method = POST) {
          proxy_pass http://books-post-service.default.svc.cluster.local:8080;
        }
        if ($request_method = PUT) {
          proxy_pass http://books-put-service.default.svc.cluster.local:8080;
        }
        if ($request_method = DELETE) {
          proxy_pass http://books-delete-service.default.svc.cluster.local:8080;
        }
        {{else}}
        proxy_pass http://{{$path.Backend.ServiceName}}.{{$ingress.Namespace}}.svc.cluster.local:{{$path.Backend.ServicePort}};
        {{end}}
      }
      {{end}}
    }
    {{end}}
    {{end}}