apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: books-ingress
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location /api/books {
        if ($request_method = GET) {
          proxy_pass http://books-get-service.default.svc.cluster.local:8080;
        }
        if ($request_method = POST) {
          proxy_pass http://books-post-service.default.svc.cluster.local:8080;
        }
        if ($request_method = PUT) {
          proxy_pass http://books-put-service.default.svc.cluster.local:8080;
        }
        if ($request_method = DELETE) {
          proxy_pass http://books-delete-service.default.svc.cluster.local:8080;
        }
      }
spec:
  ingressClassName: nginx
  rules:
  - host: books.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: books-frontend-service
              port:
                number: 8080
