apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: books-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/server-snippet: |
      location /api/books {
        if ($request_method = GET) {
          proxy_pass http://books-get-service;
        }
        if ($request_method = POST) {
          proxy_pass http://books-post-service;
        }
        if ($request_method = PUT) {
          proxy_pass http://books-put-service;
        }
        if ($request_method = DELETE) {
          proxy_pass http://books-delete-service;
        }
      }
spec:
  rules:
  - http:
      paths:
        # Frontend (HTML rendering)
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 80
