apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-rules
  namespace: default
data:
  server-snippet: |
    location /api/books {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      
      if ($request_method = GET) {
        proxy_pass http://books-get-service.default.svc.cluster.local:8080;
      }
      if ($request_method = POST) {
        proxy_pass http://books-post-service.default.svc.cluster.local:8080;
      }
      if ($request_method = PUT) {
        proxy_pass http://books-put-service.default.svc.cluster.local:8080;
      }
      if ($request_method = DELETE) {
        proxy_pass http://books-delete-service.default.svc.cluster.local:8080;
      }
    }