apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: books-ingress
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location /api/books {
        if ($request_method = GET) {
          proxy_pass http://get-service.default.svc.cluster.local:8080;
        }
        if ($request_method = POST) {
          proxy_pass http://post-service.default.svc.cluster.local:8080;
        }
        if ($request_method = PUT) {
          proxy_pass http://put-service.default.svc.cluster.local:8080;
        }
        if ($request_method = DELETE) {
          proxy_pass http://delete-service.default.svc.cluster.local:8080;
        }
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/books
            pathType: Prefix
            backend:
              service:
                name: placeholder-service
                port:
                  number: 8080
